name: counter_core
description: A new Dart package project.
version: 0.0.1
homepage: 'www.randomapps.com'

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  yust: ^3.10.0

dev_dependencies:
    build_runner: ^2.2.0
    dart_code_metrics: ^5.7.2
    lints: ^2.0.0
    test: ^1.22.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec